/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class perf_InterfaceJNI */

#ifndef _Included_perf_InterfaceJNI
#define _Included_perf_InterfaceJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     perf_InterfaceJNI
 * Method:    getrusageBegin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_perf_InterfaceJNI_getrusageBegin
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getrusageEnd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_perf_InterfaceJNI_getrusageEnd
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    setcountersBegin
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_perf_InterfaceJNI_setcountersBegin
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     perf_InterfaceJNI
 * Method:    setcountersEnd
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_perf_InterfaceJNI_setcountersEnd
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getru_utime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getru_1utime
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getru_stime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getru_1stime
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getmessages_delivered
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getmessages_1delivered
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getmessages_bytes_delivered
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getmessages_1bytes_1delivered
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    gettrains_bytes_received
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_gettrains_1bytes_1received
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    gettrains_received
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_gettrains_1received
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getrecent_trains_received
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getrecent_1trains_1received
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getrecent_trains_bytes_received
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getrecent_1trains_1bytes_1received
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getwagons_delivered
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getwagons_1delivered
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getwait_states
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getwait_1states
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1read
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_read_bytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1read_1bytes
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_readFully
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1readFully
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_readFully_bytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1readFully_1bytes
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_write
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1write
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_write_bytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1write_1bytes
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_writev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1writev
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getcomm_writev_bytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getcomm_1writev_1bytes
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getnewmsg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getnewmsg
  (JNIEnv *, jobject);

/*
 * Class:     perf_InterfaceJNI
 * Method:    getflowControl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_perf_InterfaceJNI_getflowControl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
