/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trains_Interface */

#ifndef _Included_trains_Interface
#define _Included_trains_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trains_Interface
 * Method:    trInit
 * Signature: (IIIILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_trInit
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring, jstring);

/*
 * Class:     trains_Interface
 * Method:    trError_at_line
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_trError_1at_1line
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     trains_Interface
 * Method:    trPerror
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_trPerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     trains_Interface
 * Method:    trTerminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_trTerminate
  (JNIEnv *, jobject);

/*
 * Class:     trains_Interface
 * Method:    newmsg
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_newmsg
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     trains_Interface
 * Method:    utoBroadcast
 * Signature: (Ltrains/Message;)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_utoBroadcast
  (JNIEnv *, jobject, jobject);

/*
 * Class:     trains_Interface
 * Method:    getMAX_MEMB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_getMAX_1MEMB
  (JNIEnv *, jclass);

/*
 * Class:     trains_Interface
 * Method:    getMyAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_getMyAddress
  (JNIEnv *, jclass);

/*
 * Class:     trains_Interface
 * Method:    initIDsMessageHeader
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_trains_Interface_initIDsMessageHeader
  (JNIEnv *, jclass);

/*
 * Class:     trains_Interface
 * Method:    initIDsMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_trains_Interface_initIDsMessage
  (JNIEnv *, jclass);

/*
 * Class:     trains_Interface
 * Method:    initIDsCircuitView
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_trains_Interface_initIDsCircuitView
  (JNIEnv *, jclass);

/*
 * Class:     trains_Interface
 * Method:    dumpCountersData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_dumpCountersData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
