/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trains_Interface */

#ifndef _Included_trains_Interface
#define _Included_trains_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trains_Interface
 * Method:    trInit
 * Signature: (IIIILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_trInit
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring, jstring);

/*
 * Class:     trains_Interface
 * Method:    trError_at_line
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_trError_1at_1line
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     trains_Interface
 * Method:    trPerror
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_trPerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     trains_Interface
 * Method:    trTerminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_trTerminate
  (JNIEnv *, jobject);

/*
 * Class:     trains_Interface
 * Method:    newmsg
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_newmsg
  (JNIEnv *, jobject, jint);

/*
 * Class:     trains_Interface
 * Method:    utoBroadcast
 * Signature: (Ltrains/Message;)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_utoBroadcast
  (JNIEnv *, jobject, jobject);

/*
 * Class:     trains_Interface
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_trains_Interface_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
