/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trains_Interface */

#ifndef _Included_trains_Interface
#define _Included_trains_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trains_Interface
 * Method:    trInit
 * Signature: (IIIILtrains/CallbackCircuitChange;Ltrains/CallbackUtoDeliver;)I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_trInit
  (JNIEnv *, jobject, jint, jint, jint, jint, jobject, jobject);

/*
 * Class:     trains_Interface
 * Method:    trError_at_line
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_trError_1at_1line
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     trains_Interface
 * Method:    trPerror
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_trains_Interface_trPerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     trains_Interface
 * Method:    trTerminate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_trains_Interface_trTerminate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
